#!/usr/bin/env bash
set -euo pipefail
source "${AUTOMATION_ROOT:-~/automation}/scripts/lib.sh"
MODE=""; LOCAL_CHECK_TIMEOUT="${LOCAL_CHECK_TIMEOUT:-45m}"; CI_TIMEOUT="${CI_TIMEOUT:-45m}"
while [[ $# -gt 0 ]]; do case "$1" in --mode) MODE="$2"; shift 2;; *) echo "Unknown arg: $1" >&2; exit 2;; esac; done
[[ -n "$MODE" ]] || { echo "Missing --mode" >&2; exit 2; }
require_cmd gh; require_cmd jq; require_cmd sha256sum; require_cmd base64; require_cmd timeout; require_cmd python3; init_gh_env
CURRENT=".codex-run/current"; STATE="$CURRENT/state.json"; [[ -f "$STATE" ]] || { echo "Missing state: $STATE" >&2; exit 1; }
state_get(){ jq -r "$1" "$STATE"; }
state_set(){ local f="$1" tmp; tmp=$(mktemp); jq "$f" "$STATE" > "$tmp"; mv "$tmp" "$STATE"; }
render_implementer(){ [[ -f "$CURRENT/plan.md" ]] || { echo "Missing $CURRENT/plan.md" >&2; exit 1; }; printf '%s' "$(cat "$CURRENT/issue.md")" > "$CURRENT/.issue.tmp"; printf '%s' "$(cat "$CURRENT/plan.md")" > "$CURRENT/.plan.tmp"; printf '%s' "$(state_get '.LocalCheck')" > "$CURRENT/.local-check.tmp"; printf '%s' "$(state_get '.StackContext')" > "$CURRENT/.stack-context.tmp"; render_file "$PROMPT_DIR/implementer.md" "$CURRENT/implementer.md" IssueText "$CURRENT/.issue.tmp" Plan "$CURRENT/.plan.tmp" LocalCheck "$CURRENT/.local-check.tmp" StackContext "$CURRENT/.stack-context.tmp"; rm -f "$CURRENT"/.issue.tmp "$CURRENT"/.plan.tmp "$CURRENT"/.local-check.tmp "$CURRENT"/.stack-context.tmp; state_set '.Status="ImplementerPromptRendered"'; echo "RENDERED_IMPLEMENTER_PROMPT"; }
render_local_repair(){ printf '%s' "$(cat "$CURRENT/issue.md")" > "$CURRENT/.issue.tmp"; printf '%s' "$(cat "$CURRENT/local-check.log" 2>/dev/null || true)" > "$CURRENT/.failure.tmp"; printf '%s' "$(state_get '.LocalCheck')" > "$CURRENT/.local-check.tmp"; printf '%s' "$(state_get '.StackContext')" > "$CURRENT/.stack-context.tmp"; render_file "$PROMPT_DIR/local-repair.md" "$CURRENT/local-repair.md" IssueText "$CURRENT/.issue.tmp" FailureLog "$CURRENT/.failure.tmp" LocalCheck "$CURRENT/.local-check.tmp" StackContext "$CURRENT/.stack-context.tmp"; rm -f "$CURRENT"/.issue.tmp "$CURRENT"/.failure.tmp "$CURRENT"/.local-check.tmp "$CURRENT"/.stack-context.tmp; }
local_check(){ cmd="$(state_get '.LocalCheck')"; echo "Running local check: $cmd"; set +e; timeout "$LOCAL_CHECK_TIMEOUT" bash -lc "$cmd" 2>&1 | tee "$CURRENT/local-check.log"; code=${PIPESTATUS[0]}; set -e; if [[ $code -ne 0 ]]; then render_local_repair; state_set '.Status="LocalCheckFailed" | .LastLocalCheckPassed=false'; echo "LOCAL_CHECK_FAILED"; exit 10; fi; state_set '.Status="LocalCheckPassed" | .LastLocalCheckPassed=true'; echo "LOCAL_CHECK_PASSED"; }
changes_json(){ local cur baseline; cur="$CURRENT/.workspace-current.json"; baseline="$CURRENT/workspace-snapshot.json"; if [[ -n "$(state_get '.LastCommitSha')" && "$(state_get '.LastCommitSha')" != null && -f "$CURRENT/last-commit-workspace-snapshot.json" ]]; then baseline="$CURRENT/last-commit-workspace-snapshot.json"; fi; write_workspace_snapshot "$cur"; jq -n --slurpfile old "$baseline" --slurpfile cur "$cur" '($old[0]) as $old | ($cur[0]) as $cur | ([ $cur|keys_unsorted[] as $p | if ($old[$p]==null) then {Path:$p,Status:"added"} elif ($old[$p]!=$cur[$p]) then {Path:$p,Status:"modified"} else empty end ] + [ $old|keys_unsorted[] as $p | if ($cur[$p]==null) then {Path:$p,Status:"deleted"} else empty end ])'; rm -f "$cur"; }
commit_message(){ if [[ -s "$CURRENT/commit-message.txt" ]]; then head -n1 "$CURRENT/commit-message.txt" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//'; else echo "Implement issue-$(state_get '.IssueNumber'): $(state_get '.IssueTitle')"; fi; }
create_api_commit(){ local changes="$1" repo base_tree base_sha branch parent tree_base_commit msg tree_items count i; repo=$(state_get '.RepoFullName'); base_sha=$(state_get '.BaseSha'); branch=$(state_get '.BranchName'); parent=$(state_get '.LastCommitSha'); [[ -n "$parent" && "$parent" != null ]] || parent="$base_sha"; tree_base_commit=$(state_get '.CommitTreeBaseSha // empty'); [[ -n "$tree_base_commit" ]] || tree_base_commit="$parent"; base_tree=$(gh api "repos/$repo/git/commits/$tree_base_commit" --jq '.tree.sha'); msg=$(commit_message); tree_items='[]'; count=$(jq 'length' <<< "$changes"); [[ $count -eq 0 ]] && { echo ""; return; }; for i in $(seq 0 $((count-1))); do path=$(jq -r ".[$i].Path" <<< "$changes"); status=$(jq -r ".[$i].Status" <<< "$changes"); if [[ "$status" == deleted ]]; then tree_items=$(jq --arg path "$path" '. + [{path:$path,mode:"100644",type:"blob",sha:null}]' <<< "$tree_items"); else [[ -f "./$path" ]] || { echo "Missing changed file: $path" >&2; exit 1; }; content=$(base64 -w 0 "./$path"); blob=$(jq -n --arg content "$content" '{content:$content,encoding:"base64"}' | gh api "repos/$repo/git/blobs" --method POST --input - | jq -r '.sha'); tree_items=$(jq --arg path "$path" --arg sha "$blob" '. + [{path:$path,mode:"100644",type:"blob",sha:$sha}]' <<< "$tree_items"); fi; done; tree=$(jq -n --arg base_tree "$base_tree" --argjson tree "$tree_items" '{base_tree:$base_tree,tree:$tree}' | gh api "repos/$repo/git/trees" --method POST --input - | jq -r '.sha'); commit=$(jq -n --arg msg "$msg" --arg tree "$tree" --arg parent "$parent" '{message:$msg,tree:$tree,parents:[$parent]}' | gh api "repos/$repo/git/commits" --method POST --input - | jq -r '.sha'); ref_path="heads/$branch"; ref_full="refs/heads/$branch"; if gh api "repos/$repo/git/ref/$ref_path" >/dev/null 2>&1; then jq -n --arg sha "$commit" '{sha:$sha,force:false}' | gh api "repos/$repo/git/refs/$ref_path" --method PATCH --input - >/dev/null; else jq -n --arg ref "$ref_full" --arg sha "$commit" '{ref:$ref,sha:$sha}' | gh api "repos/$repo/git/refs" --method POST --input - >/dev/null; fi; echo "$commit"; }
ensure_pr(){ repo=$(state_get '.RepoFullName'); pr=$(state_get '.PrUrl'); if [[ -n "$pr" && "$pr" != null ]]; then echo "Existing PR: $pr"; return; fi; { echo "Implements:"; echo; cat "$CURRENT/issue.md"; echo; echo "Codex plan:"; echo; [[ -f "$CURRENT/plan.md" ]] && cat "$CURRENT/plan.md"; echo; echo "Local verification:"; echo '```text'; state_get '.LocalCheck'; echo '```'; } > "$CURRENT/pr-body.md"; url=$(gh pr create --repo "$repo" --base "$(state_get '.Base')" --head "$(state_get '.BranchName')" --title "$(state_get '.IssueTitle')" --body-file "$CURRENT/pr-body.md"); num=$(gh pr view "$url" --repo "$repo" --json number --jq '.number'); jq --arg url "$url" --argjson num "$num" '.PrUrl=$url | .PrNumber=$num' "$STATE" > "$STATE.tmp" && mv "$STATE.tmp" "$STATE"; echo "Created PR: $url"; }
render_ci_repair(){ printf '%s' "$(cat "$CURRENT/issue.md")" > "$CURRENT/.issue.tmp"; printf '%s' "$(cat "$CURRENT/plan.md" 2>/dev/null || true)" > "$CURRENT/.plan.tmp"; printf '%s' "$(cat "$CURRENT/ci-summary.json" 2>/dev/null || true)" > "$CURRENT/.ci.tmp"; printf '%s' "$(state_get '.LocalCheck')" > "$CURRENT/.local-check.tmp"; printf '%s' "$(state_get '.StackContext')" > "$CURRENT/.stack-context.tmp"; render_file "$PROMPT_DIR/ci-repair.md" "$CURRENT/ci-repair.md" IssueText "$CURRENT/.issue.tmp" Plan "$CURRENT/.plan.tmp" CiSummary "$CURRENT/.ci.tmp" LocalCheck "$CURRENT/.local-check.tmp" StackContext "$CURRENT/.stack-context.tmp"; rm -f "$CURRENT"/.issue.tmp "$CURRENT"/.plan.tmp "$CURRENT"/.ci.tmp "$CURRENT"/.local-check.tmp "$CURRENT"/.stack-context.tmp; }
write_ci_summary(){ local repo="$1" sha="$2"; if ! timeout 30s gh api "repos/$repo/commits/$sha/check-runs?per_page=100" --jq '[.check_runs[] | {name:.name,bucket:(if .status != "completed" then "pending" elif (.conclusion == "success" or .conclusion == "neutral" or .conclusion == "skipped") then "pass" elif (.conclusion == "cancelled" or .conclusion == "stale") then "cancel" else "fail" end),state:(.conclusion // .status),description:(.output.summary // .output.title // ""),link:.html_url}]' > "$CURRENT/ci-summary.json"; then echo '[]' > "$CURRENT/ci-summary.json"; fi; }
wait_for_ci(){ local repo="$1" num="$2" output code deadline; deadline=$((SECONDS + ${CI_DISCOVERY_TIMEOUT_SECONDS:-600})); while (( SECONDS < deadline )); do set +e; output=$(timeout 30s gh pr checks "$num" --repo "$repo" 2>&1); code=$?; set -e; if [[ "$output" != *"no checks reported"* && -n "$output" ]]; then printf '%s\n' "$output"; set +e; timeout "$CI_TIMEOUT" gh pr checks "$num" --repo "$repo" --watch --fail-fast; code=$?; set -e; return "$code"; fi; sleep 10; done; echo "No CI checks appeared before the discovery timeout." >&2; return 1; }
render_verifier(){ repo=$(state_get '.RepoFullName'); num=$(state_get '.PrNumber'); diff=$(gh pr diff "$num" --repo "$repo" || true); printf '%s' "$(cat "$CURRENT/issue.md")" > "$CURRENT/.issue.tmp"; printf '%s' "$(cat "$CURRENT/plan.md" 2>/dev/null || true)" > "$CURRENT/.plan.tmp"; printf '%s' "$diff" > "$CURRENT/.diff.tmp"; printf '%s' "$(state_get '.LocalCheck')" > "$CURRENT/.local-check.tmp"; printf '%s' "$(state_get '.StackContext')" > "$CURRENT/.stack-context.tmp"; render_file "$PROMPT_DIR/verifier.md" "$CURRENT/verifier.md" IssueText "$CURRENT/.issue.tmp" Plan "$CURRENT/.plan.tmp" Diff "$CURRENT/.diff.tmp" LocalCheck "$CURRENT/.local-check.tmp" StackContext "$CURRENT/.stack-context.tmp"; rm -f "$CURRENT"/.issue.tmp "$CURRENT"/.plan.tmp "$CURRENT"/.diff.tmp "$CURRENT"/.local-check.tmp "$CURRENT"/.stack-context.tmp; }
pr_and_ci(){ changes=$(changes_json); if [[ $(jq 'length' <<< "$changes") -eq 0 ]]; then [[ -n "$(state_get '.PrUrl')" && "$(state_get '.PrUrl')" != null ]] || { echo "No changes and no PR" >&2; exit 1; }; else echo "$changes" > "$CURRENT/changed-files.json"; sha=$(create_api_commit "$changes"); write_workspace_snapshot "$CURRENT/last-commit-workspace-snapshot.json"; jq --arg sha "$sha" '.LastCommitSha=$sha | .Status="CommittedViaGitHubApi" | del(.CommitTreeBaseSha)' "$STATE" > "$STATE.tmp" && mv "$STATE.tmp" "$STATE"; echo "Created GitHub commit: $sha"; fi; ensure_pr; repo=$(state_get '.RepoFullName'); num=$(state_get '.PrNumber'); sha=$(state_get '.LastCommitSha'); set +e; wait_for_ci "$repo" "$num"; watch_code=$?; set -e; write_ci_summary "$repo" "$sha"; if [[ $watch_code -ne 0 ]] || jq -e '[.[]|select(.bucket=="fail" or .bucket=="cancel")]|length>0' "$CURRENT/ci-summary.json" >/dev/null; then render_ci_repair; state_set '.Status="CiFailed"'; echo "CI_FAILED"; exit 20; fi; render_verifier; state_set '.Status="CiPassedVerifierPromptRendered"'; echo "CI_PASSED"; }
render_verification_repair(){ [[ -f "$CURRENT/verification-result.md" ]] || { echo "Missing verification-result.md" >&2; exit 1; }; printf '%s' "$(cat "$CURRENT/issue.md")" > "$CURRENT/.issue.tmp"; printf '%s' "$(cat "$CURRENT/plan.md" 2>/dev/null || true)" > "$CURRENT/.plan.tmp"; printf '%s' "$(cat "$CURRENT/verification-result.md")" > "$CURRENT/.verification.tmp"; printf '%s' "$(state_get '.LocalCheck')" > "$CURRENT/.local-check.tmp"; printf '%s' "$(state_get '.StackContext')" > "$CURRENT/.stack-context.tmp"; render_file "$PROMPT_DIR/verification-repair.md" "$CURRENT/verification-repair.md" IssueText "$CURRENT/.issue.tmp" Plan "$CURRENT/.plan.tmp" VerificationFailure "$CURRENT/.verification.tmp" LocalCheck "$CURRENT/.local-check.tmp" StackContext "$CURRENT/.stack-context.tmp"; rm -f "$CURRENT"/.issue.tmp "$CURRENT"/.plan.tmp "$CURRENT"/.verification.tmp "$CURRENT"/.local-check.tmp "$CURRENT"/.stack-context.tmp; state_set '.Status="VerificationRepairPromptRendered"'; echo "RENDERED_VERIFICATION_REPAIR"; }
case "$MODE" in RenderImplementerPrompt) render_implementer;; LocalCheck) local_check;; PrAndCi) pr_and_ci;; RenderVerificationRepair) render_verification_repair;; *) echo "Unknown mode: $MODE" >&2; exit 2;; esac
